import Head from 'next/head';
import React from 'react';
import Layout from '../src/containers/Layout';

function about() {
  return (
    <Layout>
      <Head>
        <title>Smart Literature Search</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      About Page
    </Layout>
  );
}

export default about;
