import Head from 'next/head';
import Layout from '../src/containers/Layout';
import 'react-toastify/dist/ReactToastify.css';
import Content from '../src/components/Content';
import { ToastContainer } from 'react-toastify';

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Smart Literature Search</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Content />
      <ToastContainer
        position='bottom-center'
        closeOnClick
        pauseOnHover
        autoClose={4000}
        hideProgressBar
      />
    </Layout>
  );
}
