import Head from 'next/head';
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from 'react-toastify';
import LoginComponent from '../src/components/Login';
import Logout from '../src/components/Logout';

export default function login() {
  return (
    <div className='h-screen flex justify-center justify-items-center'>
      <Head>
        <title>Smart Literature Search</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <LoginComponent />
      <ToastContainer
        position='bottom-center'
        closeOnClick
        pauseOnHover
        autoClose={4000}
        hideProgressBar
      />
    </div>
  );
}
